export const fetchListItems = {
  REQUEST: "FETCH_LIST_REQUEST",
  SUCCESS: "FETCH_LIST_SUCCESS",
  FAILURE: "FETCH_LIST_FAILURE"
};

export const SET_ACTIVE_ITEM = "SET_ACTIVE_ITEM";
export const SET_FILTER_STRING = "SET_FILTER_STRING";
